# Generated by Django 4.0.5 on 2022-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('excel_file', models.FileField(blank=True, upload_to='upload')),
            ],
        ),
    ]
